//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWCBatchExporter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NWCBatchExporter.Resources.Resource.fr", typeof(Resource_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir....
        /// </summary>
        public static string FormBtn_Browse {
            get {
                return ResourceManager.GetString("FormBtn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FormBtn_Cancel {
            get {
                return ResourceManager.GetString("FormBtn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocher tout.
        /// </summary>
        public static string FormBtn_CheckAll {
            get {
                return ResourceManager.GetString("FormBtn_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout décocher.
        /// </summary>
        public static string FormBtn_CheckNone {
            get {
                return ResourceManager.GetString("FormBtn_CheckNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string FormBtn_Close {
            get {
                return ResourceManager.GetString("FormBtn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défaut.
        /// </summary>
        public static string FormBtn_Default {
            get {
                return ResourceManager.GetString("FormBtn_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportation.
        /// </summary>
        public static string FormBtn_Export {
            get {
                return ResourceManager.GetString("FormBtn_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options d&apos;exportation.
        /// </summary>
        public static string FormBtn_ExportOptions {
            get {
                return ResourceManager.GetString("FormBtn_ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir des pièces de construction.
        /// </summary>
        public static string FormLbl_ConvertConstructionParts {
            get {
                return ResourceManager.GetString("FormLbl_ConvertConstructionParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir les ID d&apos;élément.
        /// </summary>
        public static string FormLbl_ConvertElementIds {
            get {
                return ResourceManager.GetString("FormLbl_ConvertElementIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir les paramètres des éléments.
        /// </summary>
        public static string FormLbl_ConvertElementParameters {
            get {
                return ResourceManager.GetString("FormLbl_ConvertElementParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir les propriétés des éléments.
        /// </summary>
        public static string FormLbl_ConvertElementProperties {
            get {
                return ResourceManager.GetString("FormLbl_ConvertElementProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir les fichiers liés.
        /// </summary>
        public static string FormLbl_ConvertLinkedFiles {
            get {
                return ResourceManager.GetString("FormLbl_ConvertLinkedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir la pièce en attribut.
        /// </summary>
        public static string FormLbl_ConvertRoomAsAttribute {
            get {
                return ResourceManager.GetString("FormLbl_ConvertRoomAsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir les URL.
        /// </summary>
        public static string FormLbl_ConvertUrls {
            get {
                return ResourceManager.GetString("FormLbl_ConvertUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordonnés.
        /// </summary>
        public static string FormLbl_Coordinates {
            get {
                return ResourceManager.GetString("FormLbl_Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diviser le fichier en niveaux.
        /// </summary>
        public static string FormLbl_DivideFileIntoLeverls {
            get {
                return ResourceManager.GetString("FormLbl_DivideFileIntoLeverls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportation.
        /// </summary>
        public static string FormLbl_Export {
            get {
                return ResourceManager.GetString("FormLbl_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter la géométrie de la pièce.
        /// </summary>
        public static string FormLbl_ExportRoomGeometry {
            get {
                return ResourceManager.GetString("FormLbl_ExportRoomGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin du dossier :.
        /// </summary>
        public static string FormLbl_FolderPath {
            get {
                return ResourceManager.GetString("FormLbl_FolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essayez de trouver les matériaux manquants.
        /// </summary>
        public static string FormLbl_TryAndFindMissingMaterials {
            get {
                return ResourceManager.GetString("FormLbl_TryAndFindMissingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vues:.
        /// </summary>
        public static string FormLbl_Views {
            get {
                return ResourceManager.GetString("FormLbl_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue(s) sélectionnée(s).
        /// </summary>
        public static string FormLbl_ViewSelected {
            get {
                return ResourceManager.GetString("FormLbl_ViewSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout.
        /// </summary>
        public static string FormLst_All {
            get {
                return ResourceManager.GetString("FormLst_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éléments.
        /// </summary>
        public static string FormLst_Elements {
            get {
                return ResourceManager.GetString("FormLst_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interne.
        /// </summary>
        public static string FormLst_Internal {
            get {
                return ResourceManager.GetString("FormLst_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle.
        /// </summary>
        public static string FormLst_Model {
            get {
                return ResourceManager.GetString("FormLst_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string FormLst_None {
            get {
                return ResourceManager.GetString("FormLst_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éléments sélectionnées.
        /// </summary>
        public static string FormLst_SelectedElements {
            get {
                return ResourceManager.GetString("FormLst_SelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partagé.
        /// </summary>
        public static string FormLst_Shared {
            get {
                return ResourceManager.GetString("FormLst_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue.
        /// </summary>
        public static string FormLst_View {
            get {
                return ResourceManager.GetString("FormLst_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir les fichiers de sortie Navisworks.
        /// </summary>
        public static string FormTitle_BrowseNavisworksOutputFiles {
            get {
                return ResourceManager.GetString("FormTitle_BrowseNavisworksOutputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportation des vues.
        /// </summary>
        public static string FormTitle_ViewsExport {
            get {
                return ResourceManager.GetString("FormTitle_ViewsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processus d&apos;exportation annulé par l&apos;utilisateur.
        /// </summary>
        public static string MsgBoxInfo_ExportProcessCanceledByTheUser {
            get {
                return ResourceManager.GetString("MsgBoxInfo_ExportProcessCanceledByTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez installer l&apos;utilitaire d&apos;exportation Autodesk Navisworks NWC avant d&apos;utiliser l&apos;exportation par lots NWC. /n/n Cliquez sur OUI si vous souhaitez être redirigé vers la page de téléchargement d&apos;Autodesk..
        /// </summary>
        public static string MsgBoxInfo_NeedInstallAutodesk {
            get {
                return ResourceManager.GetString("MsgBoxInfo_NeedInstallAutodesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet doit être enregistré avant d&apos;utiliser cet outil..
        /// </summary>
        public static string MsgBoxInfo_ProjectMustBeSaved {
            get {
                return ResourceManager.GetString("MsgBoxInfo_ProjectMustBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez d&apos;abord le chemin..
        /// </summary>
        public static string MsgBoxInfo_SelectPathFirst {
            get {
                return ResourceManager.GetString("MsgBoxInfo_SelectPathFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succès : {0} vue(s), Échec: {1} vue(s) - {2}.
        /// </summary>
        public static string MsgBoxInfo_SucessfulFailed {
            get {
                return ResourceManager.GetString("MsgBoxInfo_SucessfulFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succès : {0} vue(s), Échec: 0 vue.
        /// </summary>
        public static string MsgBoxInfo_SucessfulXFailed0 {
            get {
                return ResourceManager.GetString("MsgBoxInfo_SucessfulXFailed0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string MsgBoxTitle_Error {
            get {
                return ResourceManager.GetString("MsgBoxTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter les résultats.
        /// </summary>
        public static string MsgBoxTitle_ExportResults {
            get {
                return ResourceManager.GetString("MsgBoxTitle_ExportResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilitaire manquant.
        /// </summary>
        public static string MsgBoxTitle_MissingUtility {
            get {
                return ResourceManager.GetString("MsgBoxTitle_MissingUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet non enregistré.
        /// </summary>
        public static string MsgBoxTitle_ProjectNotSaved {
            get {
                return ResourceManager.GetString("MsgBoxTitle_ProjectNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Navisworks.
        /// </summary>
        public static string WindowsTitle_NavisworksOptions {
            get {
                return ResourceManager.GetString("WindowsTitle_NavisworksOptions", resourceCulture);
            }
        }
    }
}
