//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWCBatchExporter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NWCBatchExporter.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string FormBtn_Browse {
            get {
                return ResourceManager.GetString("FormBtn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FormBtn_Cancel {
            get {
                return ResourceManager.GetString("FormBtn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string FormBtn_CheckAll {
            get {
                return ResourceManager.GetString("FormBtn_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check None.
        /// </summary>
        public static string FormBtn_CheckNone {
            get {
                return ResourceManager.GetString("FormBtn_CheckNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FormBtn_Close {
            get {
                return ResourceManager.GetString("FormBtn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string FormBtn_Default {
            get {
                return ResourceManager.GetString("FormBtn_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string FormBtn_Export {
            get {
                return ResourceManager.GetString("FormBtn_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        public static string FormBtn_ExportOptions {
            get {
                return ResourceManager.GetString("FormBtn_ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert construction parts.
        /// </summary>
        public static string FormLbl_ConvertConstructionParts {
            get {
                return ResourceManager.GetString("FormLbl_ConvertConstructionParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert element Ids.
        /// </summary>
        public static string FormLbl_ConvertElementIds {
            get {
                return ResourceManager.GetString("FormLbl_ConvertElementIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert element parameters.
        /// </summary>
        public static string FormLbl_ConvertElementParameters {
            get {
                return ResourceManager.GetString("FormLbl_ConvertElementParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert element properties.
        /// </summary>
        public static string FormLbl_ConvertElementProperties {
            get {
                return ResourceManager.GetString("FormLbl_ConvertElementProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert linked files.
        /// </summary>
        public static string FormLbl_ConvertLinkedFiles {
            get {
                return ResourceManager.GetString("FormLbl_ConvertLinkedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert room as attribute.
        /// </summary>
        public static string FormLbl_ConvertRoomAsAttribute {
            get {
                return ResourceManager.GetString("FormLbl_ConvertRoomAsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert URLs.
        /// </summary>
        public static string FormLbl_ConvertUrls {
            get {
                return ResourceManager.GetString("FormLbl_ConvertUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string FormLbl_Coordinates {
            get {
                return ResourceManager.GetString("FormLbl_Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide File into Levels.
        /// </summary>
        public static string FormLbl_DivideFileIntoLeverls {
            get {
                return ResourceManager.GetString("FormLbl_DivideFileIntoLeverls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string FormLbl_Export {
            get {
                return ResourceManager.GetString("FormLbl_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export room geometry.
        /// </summary>
        public static string FormLbl_ExportRoomGeometry {
            get {
                return ResourceManager.GetString("FormLbl_ExportRoomGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Path :.
        /// </summary>
        public static string FormLbl_FolderPath {
            get {
                return ResourceManager.GetString("FormLbl_FolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try and find missing materials.
        /// </summary>
        public static string FormLbl_TryAndFindMissingMaterials {
            get {
                return ResourceManager.GetString("FormLbl_TryAndFindMissingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views :.
        /// </summary>
        public static string FormLbl_Views {
            get {
                return ResourceManager.GetString("FormLbl_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View(s) selected.
        /// </summary>
        public static string FormLbl_ViewSelected {
            get {
                return ResourceManager.GetString("FormLbl_ViewSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FormLst_All {
            get {
                return ResourceManager.GetString("FormLst_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        public static string FormLst_Elements {
            get {
                return ResourceManager.GetString("FormLst_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string FormLst_Internal {
            get {
                return ResourceManager.GetString("FormLst_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string FormLst_Model {
            get {
                return ResourceManager.GetString("FormLst_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FormLst_None {
            get {
                return ResourceManager.GetString("FormLst_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedElements.
        /// </summary>
        public static string FormLst_SelectedElements {
            get {
                return ResourceManager.GetString("FormLst_SelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string FormLst_Shared {
            get {
                return ResourceManager.GetString("FormLst_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string FormLst_View {
            get {
                return ResourceManager.GetString("FormLst_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Navisworks Output Files.
        /// </summary>
        public static string FormTitle_BrowseNavisworksOutputFiles {
            get {
                return ResourceManager.GetString("FormTitle_BrowseNavisworksOutputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views Export.
        /// </summary>
        public static string FormTitle_ViewsExport {
            get {
                return ResourceManager.GetString("FormTitle_ViewsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export process canceled by the user.
        /// </summary>
        public static string MsgBoxInfo_ExportProcessCanceledByTheUser {
            get {
                return ResourceManager.GetString("MsgBoxInfo_ExportProcessCanceledByTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to install the Autodesk Navisworks NWC export utility before using NWC Batch Export.\n\nClick YES if you want to be redirected to the Autodesk download page..
        /// </summary>
        public static string MsgBoxInfo_NeedInstallAutodesk {
            get {
                return ResourceManager.GetString("MsgBoxInfo_NeedInstallAutodesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project must be saved before using this tool..
        /// </summary>
        public static string MsgBoxInfo_ProjectMustBeSaved {
            get {
                return ResourceManager.GetString("MsgBoxInfo_ProjectMustBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path first..
        /// </summary>
        public static string MsgBoxInfo_SelectPathFirst {
            get {
                return ResourceManager.GetString("MsgBoxInfo_SelectPathFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessful : {0} view(s), Failed : {1} view(s) - {2}.
        /// </summary>
        public static string MsgBoxInfo_SucessfulFailed {
            get {
                return ResourceManager.GetString("MsgBoxInfo_SucessfulFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessful : {0} view(s), Failed: 0 view.
        /// </summary>
        public static string MsgBoxInfo_SucessfulXFailed0 {
            get {
                return ResourceManager.GetString("MsgBoxInfo_SucessfulXFailed0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgBoxTitle_Error {
            get {
                return ResourceManager.GetString("MsgBoxTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export results.
        /// </summary>
        public static string MsgBoxTitle_ExportResults {
            get {
                return ResourceManager.GetString("MsgBoxTitle_ExportResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing utility.
        /// </summary>
        public static string MsgBoxTitle_MissingUtility {
            get {
                return ResourceManager.GetString("MsgBoxTitle_MissingUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not saved.
        /// </summary>
        public static string MsgBoxTitle_ProjectNotSaved {
            get {
                return ResourceManager.GetString("MsgBoxTitle_ProjectNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navisworks Options.
        /// </summary>
        public static string WindowsTitle_NavisworksOptions {
            get {
                return ResourceManager.GetString("WindowsTitle_NavisworksOptions", resourceCulture);
            }
        }
    }
}
